# Generated by Django 5.2.6 on 2025-09-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=24, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_date', models.DateField()),
                ('queue_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=24)),
                ('payment_status', models.CharField(max_length=24)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.customer')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartqueue.promotion')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.queue')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.FloatField()),
                ('password', models.CharField(max_length=24)),
                ('shop_name', models.CharField(max_length=24)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartqueue.image')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop'),
        ),
        migrations.CreateModel(
            name='OpenDate',
            fields=[
                ('open_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('working_day', models.DateField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
            ],
        ),
    ]
