# Generated by Django 5.2.6 on 2026-03-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('auth', models.OneToOneField(db_column='auth_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('auth', models.OneToOneField(db_column='auth_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartqueue.image')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=24, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_rate', models.FloatField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
            ],
        ),
        migrations.CreateModel(
            name='OpenDate',
            fields=[
                ('open_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('mon_is_closed', models.BooleanField(default=False)),
                ('mon_open', models.TimeField(blank=True, null=True)),
                ('mon_close', models.TimeField(blank=True, null=True)),
                ('tue_is_closed', models.BooleanField(default=False)),
                ('tue_open', models.TimeField(blank=True, null=True)),
                ('tue_close', models.TimeField(blank=True, null=True)),
                ('wed_is_closed', models.BooleanField(default=False)),
                ('wed_open', models.TimeField(blank=True, null=True)),
                ('wed_close', models.TimeField(blank=True, null=True)),
                ('thu_is_closed', models.BooleanField(default=False)),
                ('thu_open', models.TimeField(blank=True, null=True)),
                ('thu_close', models.TimeField(blank=True, null=True)),
                ('fri_is_closed', models.BooleanField(default=False)),
                ('fri_open', models.TimeField(blank=True, null=True)),
                ('fri_close', models.TimeField(blank=True, null=True)),
                ('sat_is_closed', models.BooleanField(default=False)),
                ('sat_open', models.TimeField(blank=True, null=True)),
                ('sat_close', models.TimeField(blank=True, null=True)),
                ('sun_is_closed', models.BooleanField(default=False)),
                ('sun_open', models.TimeField(blank=True, null=True)),
                ('sun_close', models.TimeField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_date', to='smartqueue.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('pax', models.IntegerField(default=1)),
                ('queue_date', models.DateField()),
                ('queue_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('doing', 'กำลังดำเนินการ'), ('done', 'เสร็จสิ้น'), ('cancel', 'ยกเลิก')], default='doing', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.shop')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartqueue.table')),
            ],
        ),
    ]
