# Generated by Django 5.2.6 on 2026-02-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
