# Generated by Django 5.2.6 on 2026-03-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartqueue.image'),
        ),
    ]
