# Generated by Django 5.2.6 on 2025-11-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='username',
            field=models.CharField(max_length=24),
        ),
    ]
