# Generated by Django 5.2.6 on 2026-03-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendate',
            name='working_day',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='open_datetime',
        ),
        migrations.AddField(
            model_name='opendate',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opendate',
            name='working_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='opendate',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opendate',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opendate',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_dates', to='smartqueue.shop'),
        ),
    ]
