# Generated by Django 5.2.6 on 2026-03-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0002_alter_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='line_uid',
            field=models.CharField(blank=True, help_text='ไอดีสำหรับส่ง LINE แจ้งเตือน', max_length=255, null=True),
        ),
    ]
