# Generated by Django 5.2.6 on 2026-03-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartqueue', '0002_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('doing', 'กำลังดำเนินการ'), ('done', 'เสร็จสิ้น'), ('cancel', 'ยกเลิก')], default='doing', max_length=20),
        ),
    ]
